apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    color: blue   # change to green during green deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
